### ISSUE TITLE
Find a way to deal treat pro- and private plugins separately from free plugins on wordpress.org

### ISSUE THREAD

**Issue by snim2** [dxw-wordpress-plugins/mirror-gitlab-plugins#15]
In #14 we merged a new script to mirror releases in wordpress.org to repos in this organisation.

This will work for:

* Free plugins on wordpress.org
* Plugins that are not on wordpress.org (these will fail to update)
* Free plugins on wordpress.org with a private pro-plugin which is ahead (in semver terms) of the free plugin

It will /not/ work if a plugin on wordpress.org is ahead of the private or pro-version that we wish to mirror.

Ideally we would have a generic way to say that a repository here should be ignored by the mirroring script. Setting a repository topic or other piece of metadata might be a viable option, but there are a lot of repos to manually tag.

/cc @RobjS

**Comment by snim2** [comment]
We will tag any known pro-plugin repos with the repo topic `skip-mirror` as well as any others we know are not on wordpress.org

These will be:

* Plugins we know were written by dxw
* Plugins documented in ops/docs as sourced from elsewhere
* Any plugin with the word `-pro` or `-premium` in the slug

**Comment by snim2** [comment]
Plugins with `-pro` or `-premium` in slug (done):

- easy-accordion-pro
- advanced-custom-fields-pro
- events-calendar-pro
- wp-all-import-pro
- gp-file-upload-pro
- polylang-pro
- wpae-user-add-on-pro
- wp-all-export-pro
- custom-twitter-feeds-pro
- youtube-feed-pro
- twitter-widget-pro
- custom-facebook-feed-pro
- wp-smush-pro
- relevanssi-premium
- gmw-premium-settings
- pdf-embedder-premium
- wordpress-seo-premium
- insert-or-embed-articulate-content-into-wordpress-premium
- ExactMetrics-Premium
- google-analytics-premium

**Comment by snim2** [comment]
Plugins listed in ops/docs:

- [x] advanced-custom-fields-pro 
- [x] custom-twitter-feeds-pro
- [x] easy-accordion-proaccordion-pro
- [ ] gmw-premium-settings
- [ ] gravityforms-geolocation
- [ ] forgravity-advancedpermissions
- [ ] gravityforms
- [ ] gfexportentries
- [ ] gravityformszapier
- [ ] gravityperks
- [x] pdf-embedder-premium
- [ ] pdf-viewer-for-wordpress
- [x] polylang-pro
- [x] relevanssi-premium
- [ ] searchwp
- [x] events-calendar-pro
- [ ] webtoffee-gdpr-cookie-consent
- [x] wp-smush-pro
- [ ] wpmudev-updates
- [ ] hummingbird
- [x] wp-all-import-pro
- [x] wp-all-export-pro
- [ ] sitepress-multilingual-cms
- [ ] sitepress-multilingual-cms
- [x] wordpress-seo-premium
- [ ] entry-export-for-gravity-forms
- [ ] webtoffee-gdpr-cookie-consent
- [ ] cmb-field-select2

**Comment by snim2** [comment]
More gravity forms:

- [x] gravity-forms-pdf-extended
- [x] bulk-download-for-gravity-forms
- [x] gravityformssignature
- [x] gravityformsquiz
- [x] gravityformscapsulecrm
- [x] gravityformsadvancedpostcreation
- [x] gravityformspolls
- [x] gravityformsmailchimp
- [x] gravityformssurvey
- [x] gravityformsuserregistration
- [x] gravityview-importer-master
- [x] gravityformscli
- [x] ajax-upload-for-gravity-forms
- [x] acf-gravityforms-add-on
- [x] gravity-forms-custom-post-types
- [x] gravity-forms-no-captcha-recaptcha
- [x] gravityperks-old
- [x] gravity-forms-salesforce
- [x] gravity-forms-wcag-20-form-fields
- [x] gravityview-importer
- [x] gravityforms-autocomplete

**Comment by snim2** [comment]
dxw plugins, these should be deleted or moved to the main org when we do the plugin audit, but they don't need to bother the mirror:

- [x] dxw-digest
- [x] dxw-private-by-default
- [x] dxw-bbpress
- [x] dxw-security
- [x] dxw-members-only

**Comment by snim2** [comment]
Other weird things:

- [x] jl_form_theme (not sure what this is)
- [x] the-event-calendar (misnamed?)

**Comment by mattymaxwell** [comment]
Will probably need to add these as well

Divi carousel - https://www.divigear.com/plugins/carousel-module/ - [dg-divi-carousel](https://github.com/dxw-wordpress-plugins/dg-divi-carousel)
Divi disable premade layouts - https://elegantmarketplace.com/downloads/divi-disable-premade-layouts/ - [divi-disable-premade-layouts](https://github.com/dxw-wordpress-plugins/divi-disable-premade-layouts)
Divi Overlays - https://divilife.com/downloads/divi-overlays/ - [divi-overlays](https://github.com/dxw-wordpress-plugins/divi-overlays)
Divi Logo manager - https://elegantmarketplace.com/downloads/divi-logo-manager/ - [divi-logo-manager](https://github.com/dxw-wordpress-plugins/divi-logo-manager)

**Comment by snim2** [comment]
Done
